name: Generate Thumbnails and Deploy

on:
  push:
    branches:
      - main

jobs:
  generate-thumbnails:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow  # Install PIL library for image processing

      - name: Run Thumbnail Generation Script
        run: |
          python .github/generate_thumbnails.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Add thumbnail images'